### ISSUE TITLE
Local Build

### ISSUE THREAD

**Issue by abertschi** [abertschi/musikloud2#1]
@lukedirtwalker, I am writing you regarding your fork of musikloud2 for sailfish-os. You contacted me a couple of months ago [here (Soundfish)](https://github.com/abertschi/soundfish/issues/1) because I launched a project with a similar goal. Two concurrent projects don't make much sense in my opinion which is why I am asking your for a cooperation. Soundfish was just launched and is a very early state of development.

Is your fork still under active development?

I cloned the fork and built it for armv7hl with the source of qsoundcloud available. The compilation works fine. However, I get the following error at runtime which prevents me from of launching the app.

```
Sep 24 21:18:36 Jolla sshd[6968]: dispatch_protocol_error: type 128 seq 22

Sep 24 21:18:39 Jolla mapplauncherd[7373]: Booster: Failed to invoke: Booster: Loading invoked application failed: 'libqsoundcloud.so.1: cannot open shared object file: No such f...or directory'

Sep 24 21:18:39 Jolla lipstick[965]: Failed to invoke: Booster: Loading invoked application failed: 'libqsoundcloud.so.1: cannot open shared object file: No such file or directory'

Sep 24 21:18:39 Jolla mapplauncherd[1166]: Boosted process (pid=7373) exited with status 1

Sep 24 21:18:39 Jolla lipstick[965]: invoker: Invoking execution: '/usr/bin/harbour-musikloud2'

Sep 24 21:18:40 Jolla booster-silica-qt5[7407]: [D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL 

Sep 24 21:18:40 Jolla mapplauncherd[7407]: SilicaBooster: Initiate asynchronous preload.

Sep 24 21:18:48 Jolla sshd[6968]: dispatch_protocol_error: type 128 seq 23
```

The shared libraries of qsoundcloud are available under `/usr/share/harbour-musikloud2/lib` but do not seem to be found.

Cheers

**Comment by lukedirtwalker** [comment]
Did you forget DEFINES+=QSOUNDCLOUD_STATIC_LIBRARY as qmake argument?

**Comment by abertschi** [comment]
Nah, QSOUNDCLOUD_STATIC_LIBRARY is added as qmake arg. Any other hint?

**Comment by lukedirtwalker** [comment]
Hm, not sure.
Try remove this line: https://github.com/abertschi/musikloud2/blob/sailfish_port/app/app.pro#L384
and remove the lib installs:
https://github.com/abertschi/musikloud2/blob/sailfish_port/app/app.pro#L391
and the line below and adapt the INSTALL += statement by removing the lib.

But those are just some guesses, I can look at it in more detail tomorrow, if you are on irc ping me under the same username.

**Comment by lukedirtwalker** [comment]
I just amended my commit with the changes I suggested above, and for me it works fine (but it did already before) so please let me know if it works for you.

**Comment by abertschi** [comment]
Thanks for your answer. Will take a closer look tomorrow.

**Comment by abertschi** [comment]
Works like a charm. Neat!
